source 'http://rubygems.org'

gem 'capybara'
gem 'capybara-screenshot'
gem 'capybara-selenium'
gem 'cucumber'
gem 'faker'
gem 'ffi'
gem 'httparty'
gem 'json-schema', '~> 2.8', '>= 2.8.1'
gem 'nokogiri'
gem 'report_builder'
gem 'rspec'
gem 'rubocop', '~> 1.2'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'webdrivers'
